runtime: python310

instance_class: F1

## local Database
#env_variables:
#  MYSQL_USER: 'root'
#  MYSQL_PASSWORD: '1234'
#  MYSQL_DB: 'pc411'
#  MYSQL_HOST: 'localhost'


# GCP Database
env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '411pc'
  MYSQL_DB: 'pcspec'
  MYSQL_HOST: '35.238.83.162'